dist: xenial
language: python
sudo: required
python:
  - "3.7"

before_install:
  - git fetch --unshallow
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set channel_priority strict
  - conda config --add channels conda-forge
  - conda config --add channels tpeulen
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - conda install git conda-build anaconda-client jinja2 openmp
  - wget http://situs.biomachina.org/disseminate/Situs_3.1.tar.gz
  - gunzip Situs_3.1.tar.gz
  - tar xvf Situs_3.1.tar
  - cd Situs_3.1/src
  - make
  - make install

script:
  - conda install nose coverage
  - python setup.py build_ext --inplace --force
  - nosetests --with-coverage test/test_*.py

after_success:
  - OS=$TRAVIS_OS_NAME-64
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]];
    then
      anaconda upload bld-dir/**/whatsmyblob*.tar.bz2
    fi
